droidconKE/droidconKeKotlin

build-logic/convention/build.gradle.kts
=> Fix target vs compile java version

README.md
=> Updated README to 2023

.editorconfig, CONTRIBUTING.md
=> Update readme. remove trello board link

presentation/src/main/java/com/android254/presentation/activity/MainActivity.kt, presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt, presentation/src/main/java/com/android254/presentation/home/screen/HomeScreen.kt, presentation/src/main/java/com/android254/presentation/home/viewmodel/HomeViewModel.kt, presentation/src/main/java/com/android254/presentation/sessionDetails/SessionDetailsViewModel.kt, presentation/src/main/java/com/android254/presentation/sessionDetails/view/SessionDetailsScreen.kt, presentation/src/main/java/com/android254/presentation/sessions/mappers/SessionMapper.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsScreen.kt, presentation/src/test/java/com/android254/presentation/sessions/mappers/TimePeriodTest.kt
=> Removes @RequiresApi(Build.VERSION_CODES.O)

presentation/src/main/java/com/android254/presentation/common/bottomsheet/BottomSheetScaffold.kt, presentation/src/main/java/com/android254/presentation/feed/view/FeedScreen.kt, presentation/src/main/java/com/android254/presentation/sessions/components/EventDaySelectorButton.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsScreen.kt
fixes #28 
What have you tested specifically and what possible impacts/areas there are that may need retesting
by others.
https://user-images.githubusercontent.com/32500878/220823740-c83509f5-b89f-45d3-b4e3-8c85fcb7fe53.mov
=> Fixed bottom sheet scrim color

chai/src/main/java/com/droidconke/chai/components/CButtons.kt, chai/src/main/java/com/droidconke/chai/components/CText.kt, chai/src/main/java/com/droidconke/chai/utils/Alpha.kt, chai/src/main/java/com/droidconke/chai/utils/Shape.kt
Create a design system for buttons
by others._
=> Create design system for buttons.

README.md
I am updating the README.md to add Java 11 as a setup requirement. 
closes #48
=> [documentation]: Update README with Java 11 as a setup requirement

data/build.gradle.kts, data/src/main/java/com/android254/data/di/NetworkModule.kt, gradle/libs.versions.toml
=> Add Chucker For Easy Debugging of Network Requests

gradle/libs.versions.toml, presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt
=> Migrate from collectAsState to collectAsStateWithLifecycle

.github/workflows/deploy-to-playstore.yml
This PR `closes #35 `
Attempted to run a local test of the workflow in my machine and here's a screenshot to confirm that all the steps run, the job failed when attempting to upload the bundle to alpha which is ok for now :)
**My proposal:** We first push the app bundle to alpha for internal testing before upgrading it to production for the users
=> Chore: Updating app bundle package name and version number for new release in alpha

build.gradle.kts, data/src/main/java/com/android254/data/di/DispatcherModule.kt, data/src/main/java/com/android254/data/repos/AuthManager.kt, data/src/main/java/com/android254/data/repos/HomeRepoImpl.kt, data/src/main/java/com/android254/data/repos/OrganizersSource.kt, data/src/main/java/com/android254/data/repos/SessionsManager.kt, data/src/main/java/com/android254/data/repos/SpeakersManager.kt, data/src/test/java/com/android254/data/repos/AuthManagerTest.kt, data/src/test/java/com/android254/data/repos/SessionsManagerTest.kt
=> move network/database calls to IO thread

README.md
Removed the Material3 bottom sheets documentation
by others._
=> Removed the Material3 bottom sheets documentation

presentation/src/main/java/com/android254/presentation/common/navigation/Screens.kt
Fixes #17 
please check the below boxes
by others._
=> Re-Introduce Feed Tab

data/src/main/java/com/android254/data/di/DispatcherModule.kt, data/src/main/java/com/android254/data/repos/AuthManager.kt, data/src/main/java/com/android254/data/repos/HomeRepoImpl.kt, data/src/main/java/com/android254/data/repos/SessionsManager.kt, data/src/main/java/com/android254/data/repos/SpeakersManager.kt, data/src/test/java/com/android254/data/repos/SessionsManagerTest.kt, presentation/src/main/java/com/android254/presentation/feedback/view/FeedBackScreen.kt, presentation/src/main/java/com/android254/presentation/sessionDetails/SessionDetailsViewModel.kt, presentation/src/main/java/com/android254/presentation/sessionDetails/view/SessionDetailsScreen.kt, presentation/src/main/java/com/android254/presentation/sessions/components/EventDaySelector.kt, presentation/src/main/java/com/android254/presentation/sessions/components/SessionList.kt, presentation/src/main/java/com/android254/presentation/sessions/components/SessionsFilterPanel.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsViewModel.kt, presentation/src/test/java/com/android254/presentation/feedback/view/FeedBackScreenTest.kt
=> Fix FeedbackScreen appbar scrollbehaviour

presentation/src/main/java/com/android254/presentation/activity/MainActivity.kt, presentation/src/main/java/com/android254/presentation/common/components/SessionsCard.kt, presentation/src/main/java/com/android254/presentation/sessions/components/SessionStateComponent.kt, presentation/src/main/java/com/android254/presentation/sessions/models/SessionsUiState.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsScreen.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsViewModel.kt
=> Attempt To Fix CI

data/src/test/java/com/android254/data/dao/SessionDaoTest.kt, presentation/src/test/java/com/android254/presentation/sessionDetails/view/SessionDetailsScreenTest.kt
=> Fix Broken SessionDetails Screen UI Test Cases

presentation/src/main/java/com/android254/presentation/feed/view/FeedComponent.kt, presentation/src/main/java/com/android254/presentation/feed/view/FeedScreen.kt, presentation/src/main/java/com/android254/presentation/feed/view/FeedShareSection.kt
=> Update feedback previews to use ChaiTheme

README.md, chai/src/main/java/com/droidconke/chai/atoms/Color.kt, data/src/test/java/com/android254/data/dao/SessionDaoTest.kt, presentation/src/main/java/com/android254/presentation/common/bottomnav/BottomNavigationBar.kt, presentation/src/test/java/com/android254/presentation/sessionDetails/view/SessionDetailsScreenTest.kt
=> changes BottomAppBar background color

chai/src/main/java/com/droidconke/chai/Theme.kt, chai/src/main/java/com/droidconke/chai/colors/ChaiColors.kt, presentation/src/main/java/com/android254/presentation/home/components/HomeSessionSection.kt
=> Feature: Add custom colors palette.

data/src/main/java/com/android254/data/network/util/HttpClientFactory.kt, presentation/src/main/java/com/android254/presentation/speakers/SpeakerDetailsScreenViewModel.kt, presentation/src/main/java/com/android254/presentation/speakers/SpeakersScreenViewModel.kt, presentation/src/main/java/com/android254/presentation/speakers/view/SpeakerDetailsScreen.kt, presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt, presentation/src/test/java/com/android254/presentation/speakers/view/SpeakerDetailsScreenTest.kt, presentation/src/test/java/com/android254/presentation/speakers/view/SpeakersScreenTest.kt
In the HttpClientFactory.kt i changed the api key from the firebase remote config one because apparently the api calls were failing... I think its because of the changing of the package name in previous PRs but I'm not sure. 
The rest is as per the title
=> Migrate some State for some screens from their composables to their respective ViewModels (#111)

presentation/src/main/java/com/android254/presentation/sessions/components/SessionsFilterPanel.kt, presentation/src/main/res/values/strings.xml
=> fix label capitalization: changed 'advanced' to 'Advanced'

presentation/src/main/java/com/android254/presentation/sessions/view/SessionsViewModel.kt
=> Fixed crash on Filter Button under Sessions tab

presentation/src/main/java/com/android254/presentation/about/view/AboutScreen.kt, presentation/src/main/java/com/android254/presentation/about/view/AboutViewModel.kt, presentation/src/main/java/com/android254/presentation/home/screen/HomeScreen.kt, presentation/src/main/java/com/android254/presentation/home/viewmodel/HomeViewModel.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsViewModel.kt, presentation/src/main/java/com/android254/presentation/speakers/SpeakersScreenViewModel.kt, presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt
=> Migrate some State and viewModel calls from their composables to their respective ViewModels

presentation/src/main/java/com/android254/presentation/common/components/DroidconAppBar.kt, presentation/src/main/java/com/android254/presentation/common/components/DroidconAppBarWithFeedbackButton.kt, presentation/src/main/java/com/android254/presentation/common/components/DroidconAppBarWithFilter.kt, presentation/src/main/java/com/android254/presentation/common/components/ToggleButtonGroup.kt, presentation/src/main/java/com/android254/presentation/sessions/components/SessionsFilterPanel.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsScreen.kt, presentation/src/test/java/com/android254/presentation/speakers/view/SpeakerDetailsScreenTest.kt
=> Feature: Enhance lint.

build-logic/convention/build.gradle.kts, build-logic/convention/src/main/kotlin/AndroidRoomConventionPlugin.kt, data/build.gradle.kts, gradle/libs.versions.toml
Closes one section of issue 33
Working on this with @jumaallan 
No screenshot required, just confirmed the app is running on Android studio.
=> WIP: Room dependency migration to convention plugin

README.md
=> contrib-readme-action has updated readme

build-logic/convention/build.gradle.kts, build-logic/convention/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt, build-logic/convention/src/main/kotlin/com/android254/AndroidCompose.kt, chai/build.gradle.kts, chai/src/main/java/com/droidconke/chai/Theme.kt, gradle/libs.versions.toml, presentation/build.gradle.kts, presentation/src/main/java/com/android254/presentation/feed/view/FeedScreen.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsScreen.kt
Fixes part of issue33
by others._
=> Feat: Migrate all compose dependencies to convention plugin

app/build.gradle.kts, build-logic/convention/build.gradle.kts, build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidLibraryFirebaseConventionPlugin.kt, data/build.gradle.kts, gradle/libs.versions.toml, presentation/src/main/java/com/android254/presentation/feed/view/FeedScreen.kt
Fixes part of issue33
by others._
=> 36 create firebase convention plugin

app/build.gradle.kts, build-logic/convention/build.gradle.kts, build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Fixes part of issue 33
by others._
=> Feat: Migrated Kotlin Application dependencies to convention plugin

.github/workflows/deploy-to-playstore.yml, whatsnew/whatsnew-en-US
=> Fixes deploy to Playstore workflow.

README.md
=> Update README.md - Update Java Requirements

README.md, presentation/src/main/java/com/android254/presentation/about/view/AboutScreen.kt, presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt, presentation/src/main/java/com/android254/presentation/feed/view/FeedScreen.kt, presentation/src/main/java/com/android254/presentation/feedback/view/FeedBackScreen.kt, presentation/src/main/java/com/android254/presentation/home/screen/HomeScreen.kt, presentation/src/main/java/com/android254/presentation/sessionDetails/view/SessionDetailsScreen.kt, presentation/src/main/java/com/android254/presentation/sessions/components/EventDaySelector.kt, presentation/src/main/java/com/android254/presentation/sessions/components/SessionsFilterPanel.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsScreen.kt, presentation/src/main/java/com/android254/presentation/speakers/view/SpeakerDetailsScreen.kt, presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt, presentation/src/test/java/com/android254/presentation/about/view/AboutScreenTest.kt, presentation/src/test/java/com/android254/presentation/feed/view/FeedScreenTest.kt, presentation/src/test/java/com/android254/presentation/feedback/view/FeedBackScreenTest.kt, presentation/src/test/java/com/android254/presentation/sessionDetails/view/SessionDetailsScreenTest.kt, presentation/src/test/java/com/android254/presentation/sessions/view/SessionScreenTest.kt, presentation/src/test/java/com/android254/presentation/speakers/view/SpeakerDetailsScreenTest.kt, presentation/src/test/java/com/android254/presentation/speakers/view/SpeakersScreenTest.kt
=> Fix preview

app/build.gradle.kts, app/proguard-rules.pro
=> Feature: Minify release.

presentation/src/main/java/com/android254/presentation/feed/view/FeedComponent.kt
=> Closes #199 Fixing Dark Mode on Feed Screen

presentation/src/main/java/com/android254/presentation/speakers/view/SpeakersScreen.kt
Fix for this [issue ](https://github.com/droidconKE/droidconKeKotlin/issues/138)
=> color changes upon changing theme

presentation/src/main/java/com/android254/presentation/home/components/HomeSpeakerComponent.kt, presentation/src/main/java/com/android254/presentation/speakers/view/SpeakerComponent.kt
=> fix border color

presentation/src/main/java/com/android254/presentation/about/view/AboutScreen.kt
=> fixing organizing team spacing

chai/src/main/java/com/droidconke/chai/atoms/Color.kt, chai/src/main/java/com/droidconke/chai/colors/ChaiColors.kt, presentation/src/main/java/com/android254/presentation/common/components/SponsorsCard.kt, presentation/src/main/java/com/android254/presentation/home/components/HomeSectionHeaderComponent.kt, presentation/src/main/java/com/android254/presentation/home/components/HomeSessionSection.kt, presentation/src/main/java/com/android254/presentation/home/components/HomeSpeakerComponent.kt, presentation/src/main/java/com/android254/presentation/home/components/HomeSpeakersSection.kt, presentation/src/main/java/com/android254/presentation/home/screen/HomeScreen.kt, presentation/src/test/java/com/android254/presentation/home/screen/HomeScreenTest.kt
=> Refactor: Cleanup home section

presentation/src/main/java/com/android254/presentation/common/navigation/Navigation.kt, presentation/src/main/java/com/android254/presentation/home/components/HomeSessionSection.kt, presentation/src/main/java/com/android254/presentation/home/screen/HomeScreen.kt
=> Fixes #193

presentation/src/main/res/values/strings.xml
- [ x] I have followed the coding conventions
- [x ] I have added/updated necessary tests
- [ x] I have tested the changes added on a physical device
- [ x] I have run `./codeAnalysis.sh` on linux/unix or `codeAnalysys.bat` on windows to make sure all lint/formatting checks have been done.
_What have you tested specifically and what possible impacts/areas there are that may need …
=> Updated the About page content

presentation/src/main/java/com/android254/presentation/home/viewmodel/HomeViewModel.kt
=> Fixes #190

.github/workflows/gradle-wrapper.yml
=> Validate the gradle wrapper on a PR

README.md
Refactor the deeplink for the designs links that were not nested properly in markdown
`closes #240  `
by others._
=> Issue/#240 Refactor

app/src/main/AndroidManifest.xml, data/src/main/java/com/android254/data/work/SyncDataWorker.kt, datasource/remote/src/main/java/ke/droidcon/kotlin/datasource/remote/Constants.kt, gradle/libs.versions.toml
=> Fix: Cannot create Work-Manager

chai/src/main/java/com/droidconke/chai/colors/ChaiColors.kt, presentation/src/main/java/com/android254/presentation/sessions/components/EventDaySelector.kt, presentation/src/main/java/com/android254/presentation/sessions/components/EventDaySelectorButton.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsScreen.kt, presentation/src/main/java/com/android254/presentation/utils/ChaiLightAndDarkComposePreview.kt
=> Fix: Event date fix to match designs

data/src/main/java/com/android254/data/repos/mappers/SessionMapper.kt, domain/src/main/java/com/android254/domain/models/Session.kt, presentation/src/main/java/com/android254/presentation/home/viewmodel/HomeViewModel.kt, presentation/src/main/java/com/android254/presentation/models/SessionPresentationModel.kt, presentation/src/main/java/com/android254/presentation/sessions/mappers/SessionMapper.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsViewModel.kt, presentation/src/test/java/com/android254/presentation/sessionDetails/view/SessionDetailsScreenTest.kt
=> Fix: Event Date selector switch

data/src/main/java/com/android254/data/repos/OrganizersManager.kt
=> Fix: Duplicate organizers.

data/src/main/java/com/android254/data/repos/SessionsManager.kt, domain/src/main/java/com/android254/domain/models/SessionFilter.kt, domain/src/main/java/com/android254/domain/repos/SessionsRepo.kt, presentation/src/main/java/com/android254/presentation/sessions/components/SessionsFilterPanel.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsViewModel.kt
=> refactor: Improve logic for filtering

app/src/main/AndroidManifest.xml, app/src/main/res/values/colors.xml, presentation/build.gradle.kts, presentation/src/main/java/com/android254/presentation/activity/MainActivity.kt, presentation/src/main/java/com/android254/presentation/di/PresentationModule.kt, presentation/src/main/java/com/android254/presentation/notifications/DroidconNotificationManager.kt, presentation/src/main/java/com/android254/presentation/notifications/MessagingService.kt
=> Feature: Push notifications.

presentation/src/main/java/com/android254/presentation/sessions/mappers/SessionMapper.kt, presentation/src/main/java/com/android254/presentation/sessions/models/SessionsUiState.kt, presentation/src/main/java/com/android254/presentation/sessions/view/SessionsViewModel.kt, presentation/src/main/java/com/android254/presentation/utils/DateAndTimeUtils.kt
=> refactor: UI Improvements

.github/workflows/branch.yml, .gitignore, app/build.gradle.kts, build-logic/convention/src/main/kotlin/com/android254/KotlinAndroid.kt, build-logic/gradle/wrapper/gradle-wrapper.properties, build.gradle.kts, data/build.gradle.kts, data/src/main/java/com/android254/data/repos/SpeakersManager.kt, datasource/local/build.gradle.kts, datasource/local/src/main/java/ke/droidcon/kotlin/datasource/local/dao/SpeakerDao.kt, datasource/local/src/main/java/ke/droidcon/kotlin/datasource/local/source/LocalSpeakersDataSource.kt, datasource/local/src/main/java/ke/droidcon/kotlin/datasource/local/source/LocalSpeakersDataSourceImpl.kt, datasource/remote/build.gradle.kts, domain/src/main/java/com/android254/domain/repos/SpeakersRepo.kt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, presentation/build.gradle.kts, presentation/src/main/java/com/android254/presentation/speakers/SpeakerDetailsScreenViewModel.kt, presentation/src/test/java/com/android254/presentation/speakers/view/SpeakerDetailsScreenTest.kt, settings.gradle.kts, shared/build.gradle.kts, shared/data/build.gradle.kts, shared/datasource/build.gradle.kts, shared/domain/build.gradle.kts, shared/shared.podspec
This PR sets up KMM modules. ie. Data, Domain and Data Source.
by others._
=> Feature: Setup KMM

.gitignore
=> Add .kotlin folder to git ignore

.github/workflows/main.yml
=> Fix: Failing CI

app/src/main/java/com/android254/droidconKE2023/app/DroidconKE2023App.kt, presentation/src/main/java/com/android254/presentation/common/components/DroidConTextField.kt, presentation/src/main/java/com/android254/presentation/sessionDetails/view/SessionDetailsScreen.kt
Fix: Initialize WorkManager configuration after Hilt injection
The `workerFactory` was being accessed before it was initialized by Hilt,
leading to an `UninitializedPropertyAccessException`. This occurred because
`workManagerConfiguration` was initialized during the application's
construction phase, prior to Hilt completing its dependency injection.
To resolve this, the initialization of the `workManagerConfiguration`
(specifically, its backing property) is now deferred until the `onCreate()`
lifecycle method of the `Application` class. At this point, Hilt has
completed its injection process, ensuring that `workerFactory` is
properly provided and ready for use.
This should Resolve resolve  #319 
_Please make sure to read the [Contribution …
=>  Refactoring APIs based on latest libs versions And fix lateinit property workerFactory has not been initialized PropertyAccessException
